# Generated by Django 3.0.8 on 2021-07-02 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
                ('suggestion', models.TextField()),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.Meal')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('option', models.CharField(max_length=200)),
                ('scheduled', models.DateField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('meals', models.ManyToManyField(to='dashboard.Meal')),
            ],
        ),
    ]
