# Generated by Django 3.0.8 on 2021-07-03 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210703_0322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='celery_status',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='celery_task_id',
        ),
        migrations.CreateModel(
            name='TaskMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=200)),
                ('celery_status', models.IntegerField(default=0)),
                ('menu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Menu')),
            ],
        ),
    ]
