# Generated by Django 3.0.8 on 2021-07-03 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20210703_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
