# Generated by Django 3.0.8 on 2021-07-06 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_delete_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmenu',
            name='menu',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='dashboard.Menu'),
        ),
    ]
